### ISSUE TITLE
Framework fails to register with newly elected master because a blockingqueue is full

### ISSUE THREAD

**Issue by verma7** [mesosphere/dcos-cassandra-service#372]
I am getting the following exception sometimes when there is a Mesos master re-election:

```
ERROR [2017-01-14 12:12:44,758] com.mesosphere.dcos.cassandra.scheduler.CassandraScheduler: An error occurred when registering the framework and initializing the execution plan.
! java.lang.IllegalStateException: Queue full
! at java.util.AbstractQueue.add(AbstractQueue.java:98) ~[na:1.8.0_112]
! at java.util.concurrent.ArrayBlockingQueue.add(ArrayBlockingQueue.java:312) ~[na:1.8.0_112]
! at com.mesosphere.dcos.cassandra.scheduler.CassandraScheduler.registered(CassandraScheduler.java:169) ~[cassandra-scheduler.jar:na]
```

It looks like this queue is becoming full here: https://github.com/mesosphere/dcos-cassandra-service/blob/099da9533adc8f180191fbf1155d31334da6089d/cassandra-scheduler/src/main/java/com/mesosphere/dcos/cassandra/scheduler/CassandraScheduler.java#L81 because `getResources()` is called only once but `registered()` is being called multiple times when the Mesos master gets re-elected.

Please see 
https://issues.apache.org/jira/browse/MESOS-786
https://issues.apache.org/jira/browse/MESOS-6249
for details of register() and re-register() semantics.

**Comment by verma7** [comment]
The fix #374 has been merged.
